### ISSUE TITLE
Add book link to main navigation

### ISSUE THREAD

**Issue by naturallymitchell** [actix/actix-website#82]
actix.rs currently lacks a featured link to this great resource, [Actix Book](https://actix.rs/book/actix/).

**Comment by Firstyear** [comment]
@DoumanAsh Would you mind adding this link to the website? I'm not very confident to add this link myself, and I think that this is a great point that the actix book should be more discoverable.

**Comment by DoumanAsh** [comment]
Well actix.rs was more aimed at `actix-web` actually.
We can link, but book is not finished anyway, so I'm not sure if it is good idea until it is finished at least.

**Comment by Firstyear** [comment]
Well, like any good project, will the book truly every be finished .... *looks to the horizon* ...

I think that perhaps a solution to this problem is to link the book, and in the book contents we just unlike the WIP chapters. Previously almost all of the book was WIP, now we have I think 3 or 4 to go. 

So if we just hide the WIP sections, we can link what we have now, which is already a huge improvement to educational resources. 

What do you think?

**Comment by DoumanAsh** [comment]
Well, I guess we can add the link to book in welcome page as it is done for actix's API docs https://github.com/actix/actix-website/blob/master/content/docs/_index.md

**Comment by dewey4iv** [comment]
Just throwing in my 2¢ here... 

@DoumanAsh - I agree, it looks like https://actix.rs _is_ more aimed at `actix-web` -- though, it would be nice to see that change. Especially since the sizable change from 0.7 -> 1.0 of actix-web.

I tend to agree with @Firstyear: A link to the book (that I didn't know existed until yesterday) _even_ in an unfinished state is more helpful than nothing at all. Including it seems like a good idea if for no other reason than to encourage someone to continue working on it.

**Comment by naturallymitchell** [comment]
this is an important issue https://github.com/actix/actix-web/issues/1291

**Comment by robjtede** [comment]
actors are continuing to take a back seat, all documentation for `actix` should live in-tree and on it's rustdoc
